CREATE TABLE [dbo].[fb_empresa_especializada] (
    [fb_empresa_especializada_id]   NUMERIC (10)   IDENTITY (1, 1) NOT NULL,
    [razon_social]                  NVARCHAR (500) NULL,
    [ruc_empresa]                   NVARCHAR (20)  NULL,
    [codigo]                        NVARCHAR (50)  NULL,
    [representante_legal]           NVARCHAR (200) NULL,
    [direccion]                     NVARCHAR (200) NULL,
    [telefono_1]                    NVARCHAR (100) NULL,
    [telefono_2]                    NVARCHAR (100) NULL,
    [descripcion]                   NVARCHAR (300) NULL,
    [fax]                           NVARCHAR (50)  NULL,
    [email]                         NVARCHAR (50)  NULL,
    [url]                           NVARCHAR (200) NULL,
    [movil]                         NVARCHAR (50)  NULL,
    [estado]                        NUMERIC (1)    NULL,
    [fb_uea_pe_id]                  NUMERIC (10)   NULL,
    [fecha_inicio]                  DATETIME       NULL,
    [fecha_fin]                     DATETIME       NULL,
    [created]                       DATETIME       NULL,
    [created_by]                    NUMERIC (10)   NULL,
    [updated]                       DATETIME       NULL,
    [updated_by]                    NUMERIC (10)   NULL,
    [owner_id]                      NUMERIC (10)   NULL,
    [is_deleted]                    NUMERIC (1)    NULL,
    [codCiaRel]                     NVARCHAR (4)   NULL,
    [ruc]                           NVARCHAR (20)  NULL,
    [g_actividad_minera_id]         NUMERIC (10)   NULL,
    [g_rol_empresa_id]              NUMERIC (10)   NULL,
    [tipo_empresa]                  NUMERIC (1)    NULL,
    [anno_inicio_actividad]         VARCHAR (25)   NULL,
    [g_actividad_economica_ciiu_id] NUMERIC (10)   NULL,
    [creado]                        DATETIME       NULL,
    [creado_por]                    NUMERIC (10)   NULL,
    [actualizado]                   DATETIME       NULL,
    [actualizado_por]               NUMERIC (10)   NULL,
    [propietario_id]                NUMERIC (10)   NULL,
    [tipo]                          NUMERIC (1)    NULL,
    [codigo_departamento]           VARCHAR (50)   NULL,
    [codigo_municipio]              VARCHAR (50)   NULL,
    [fb_tipo_identificacion_id]     NUMERIC (10)   NULL,
    [fb_ubicacion_id]               NUMERIC (10)   NULL,
    [municipio]                     VARCHAR (50)   NULL,
    [zona]                          VARCHAR (50)   NULL,
    CONSTRAINT [PK_fb_empresa_especializada] PRIMARY KEY CLUSTERED ([fb_empresa_especializada_id] ASC)
);


GO

