CREATE TABLE [dbo].[FB_HISTORY] (
    [FB_HISTORY_ID] NUMERIC (10)   IDENTITY (1, 1) NOT NULL,
    [CODE]          NVARCHAR (100) NULL,
    [NAME]          NVARCHAR (100) NULL,
    [IS_DELETED]    NUMERIC (1)    NULL,
    [CREATED]       DATETIME       NULL,
    [UPDATED]       DATETIME       NULL,
    [CREATED_BY]    NUMERIC (10)   NULL,
    [UPDATED_BY]    NUMERIC (10)   NULL,
    [OWNER_ID]      NUMERIC (10)   NULL,
    CONSTRAINT [PK_FB_HISTORY] PRIMARY KEY CLUSTERED ([FB_HISTORY_ID] ASC)
);


GO

