CREATE TABLE [dbo].[fb_proceso] (
    [fb_proceso_id]                        NUMERIC (10)  IDENTITY (1, 1) NOT NULL,
    [codigo]                               VARCHAR (50)  NULL,
    [titulo]                               VARCHAR (200) NULL,
    [descripcion]                          VARCHAR (500) NULL,
    [tipo_proceso]                         VARCHAR (200) NULL,
    [sp_proceso]                           VARCHAR (200) NULL,
    [Flag_Estado]                          VARCHAR (50)  NULL,
    [created]                              DATETIME      NULL,
    [created_by]                           NUMERIC (10)  NULL,
    [updated]                              DATETIME      NULL,
    [updated_by]                           NUMERIC (10)  NULL,
    [owner_id]                             NUMERIC (10)  NULL,
    [is_deleted]                           NUMERIC (1)   NULL,
    [tipo_frecuencia]                      VARCHAR (200) NULL,
    [recurrencia_diario]                   INT           NULL,
    [recurrencia_semanal]                  INT           NULL,
    [lunes]                                NUMERIC (1)   NULL,
    [martes]                               NUMERIC (1)   NULL,
    [miercoles]                            NUMERIC (1)   NULL,
    [jueves]                               NUMERIC (1)   NULL,
    [viernes]                              NUMERIC (1)   NULL,
    [sabado]                               NUMERIC (1)   NULL,
    [domingo]                              NUMERIC (1)   NULL,
    [frec_men_opc_dia]                     NUMERIC (1)   NULL,
    [frec_men_opc_dia_conf_dia]            INT           NULL,
    [frec_men_opc_dia_conf_mes]            INT           NULL,
    [frec_men_opc_esp]                     NUMERIC (1)   NULL,
    [frec_men_opc_esp_conf_ord_dia]        VARCHAR (200) NULL,
    [frec_men_opc_esp_conf_dia_sem]        VARCHAR (200) NULL,
    [frec_men_opc_esp_conf_mes]            INT           NULL,
    [frec_dia_opc_una]                     NUMERIC (1)   NULL,
    [frec_dia_opc_una_conf_hora]           VARCHAR (10)  NULL,
    [frec_dia_opc_rec]                     NUMERIC (1)   NULL,
    [frec_dia_opc_rec_conf_int_hora]       INT           NULL,
    [frec_dia_opc_rec_conf_int_hora_desde] VARCHAR (10)  NULL,
    [frec_dia_opc_rec_conf_int_hora_hasta] VARCHAR (10)  NULL,
    [periodo_desde]                        DATETIME      NULL,
    [periodo_hasta_opc_si]                 NUMERIC (1)   NULL,
    [periodo_hasta_opc_si_conf_dia]        DATETIME      NULL,
    [periodo_hasta_opc_no]                 NUMERIC (1)   NULL,
    CONSTRAINT [PK_fb_proceso] PRIMARY KEY CLUSTERED ([fb_proceso_id] ASC)
);


GO

