CREATE TABLE [dbo].[inc_informe_final_dano_primax] (
    [inc_informe_final_dano_primax_id] NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [inc_informe_final_id]             NUMERIC (10)    NULL,
    [maquinarias]                      VARCHAR (50)    NULL,
    [fuente_dano]                      VARCHAR (200)   NULL,
    [dano]                             VARCHAR (500)   NULL,
    [licencia]                         VARCHAR (50)    NULL,
    [placa]                            VARCHAR (50)    NULL,
    [modelo]                           VARCHAR (50)    NULL,
    [ano_fabricacion]                  VARCHAR (50)    NULL,
    [nombre_conductor]                 VARCHAR (200)   NULL,
    [oficio_cargo]                     VARCHAR (50)    NULL,
    [edad]                             NUMERIC (10)    NULL,
    [inc_grado_instruccion_id]         NUMERIC (10)    NULL,
    [procedencia]                      VARCHAR (50)    NULL,
    [fb_empresa_especializada_id]      NUMERIC (10)    NULL,
    [fecha_ingreso]                    DATETIME        NULL,
    [experiencia_uea_aa]               NUMERIC (2)     NULL,
    [experiencia_uea_mm]               NUMERIC (2)     NULL,
    [experiencia_uea_formateada]       VARCHAR (50)    NULL,
    [experiencia_ocupacion_aa]         NUMERIC (2)     NULL,
    [experiencia_ocupacion_mm]         NUMERIC (2)     NULL,
    [experiencia_ocupacion_formateada] VARCHAR (50)    NULL,
    [otros_vehiculo]                   VARCHAR (200)   NULL,
    [danos]                            VARCHAR (500)   NULL,
    [tipo_material]                    VARCHAR (50)    NULL,
    [volumen_derramado]                VARCHAR (50)    NULL,
    [volumen_recuperado]               VARCHAR (50)    NULL,
    [otros_derrame]                    VARCHAR (50)    NULL,
    [marcha]                           VARCHAR (50)    NULL,
    [explique]                         VARCHAR (500)   NULL,
    [inc_severidad_potencial_id]       NUMERIC (10)    NULL,
    [inc_probabilidad_recurrencia_id]  NUMERIC (10)    NULL,
    [inc_frecuencia_exposicion_id]     NUMERIC (10)    NULL,
    [conclusiones]                     VARCHAR (500)   NULL,
    [costo_accidente]                  NUMERIC (15, 3) NULL,
    [lugar_afectado]                   VARCHAR (5000)  NULL,
    [impacto_material]                 VARCHAR (50)    NULL,
    [tiempo_perdido]                   VARCHAR (50)    NULL,
    [ruptura_stock]                    VARCHAR (50)    NULL,
    [cantidad_contaminado]             VARCHAR (50)    NULL,
    [cantidad_merma]                   VARCHAR (50)    NULL,
    [incumplio_acuerdo]                VARCHAR (50)    NULL,
    [created]                          DATETIME        NULL,
    [created_by]                       NUMERIC (10)    NULL,
    [updated]                          DATETIME        NULL,
    [updated_by]                       NUMERIC (10)    NULL,
    [owner_id]                         NUMERIC (10)    NULL,
    [is_deleted]                       NUMERIC (1)     NULL,
    [g_aseguradora_id]                 NUMERIC (10)    NULL,
    [g_tipo_seguro_id]                 NUMERIC (10)    NULL,
    [numero_poliza]                    VARCHAR (50)    NULL,
    [coordenada_utm]                   VARCHAR (100)   NULL,
    CONSTRAINT [PK_inc_informe_final_dano_primax] PRIMARY KEY CLUSTERED ([inc_informe_final_dano_primax_id] ASC)
);


GO

