CREATE TABLE [dbo].[inc_informe_preliminar] (
    [inc_informe_preliminar_id]     NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [codigo]                        VARCHAR (50)    NULL,
    [fb_empresa_id]                 NUMERIC (10)    NULL,
    [inc_tipo_reporte_id]           NUMERIC (10)    NULL,
    [tipo_reporte_nombre]           VARCHAR (100)   NULL,
    [otros_reportes]                VARCHAR (50)    NULL,
    [inc_potencial_perdida_id]      NUMERIC (10)    NULL,
    [fb_empleado_id]                NUMERIC (10)    NULL,
    [empleado_codigo]               VARCHAR (50)    NULL,
    [empleado_apellido_paterno]     VARCHAR (100)   NULL,
    [empleado_apellido_materno]     VARCHAR (100)   NULL,
    [empleado_nombre]               VARCHAR (100)   NULL,
    [empleado_nombre_completo]      VARCHAR (200)   NULL,
    [fb_area_id]                    NUMERIC (10)    NULL,
    [area_nombre]                   VARCHAR (100)   NULL,
    [empleado_area_nombre]          VARCHAR (100)   NULL,
    [fecha_evento]                  DATETIME        NULL,
    [hora_evento]                   VARCHAR (25)    NULL,
    [lugar_evento]                  VARCHAR (500)   NULL,
    [tiempo_para_proceso]           NUMERIC (10)    NULL,
    [costo_probable_dano]           NUMERIC (13, 2) NULL,
    [costo_dano_propiedad]          NUMERIC (13, 2) NULL,
    [testigos]                      VARCHAR (500)   NULL,
    [inc_segun_tipo_id]             NUMERIC (10)    NULL,
    [segun_tipo_nombre]             VARCHAR (200)   NULL,
    [descripcion_evento]            VARCHAR (1000)  NULL,
    [descripcion_dano_perdida]      VARCHAR (1000)  NULL,
    [comentarios]                   VARCHAR (500)   NULL,
    [imagen_pre_evento]             VARCHAR (200)   NULL,
    [comentario_pre_evento]         VARCHAR (200)   NULL,
    [imagen_evento]                 VARCHAR (200)   NULL,
    [comentario_evento]             VARCHAR (200)   NULL,
    [inc_estado_info_preliminar_id] NUMERIC (10)    NULL,
    [codigo_informe_enviado]        VARCHAR (50)    NULL,
    [minuto_evento]                 VARCHAR (2)     NULL,
    [area_evento_nombre]            VARCHAR (100)   NULL,
    [fb_uea_pe_id]                  NUMERIC (10)    NULL,
    [created]                       DATETIME        NULL,
    [created_by]                    NUMERIC (10)    NULL,
    [updated]                       DATETIME        NULL,
    [updated_by]                    NUMERIC (10)    NULL,
    [owner_id]                      NUMERIC (10)    NULL,
    [is_deleted]                    NUMERIC (1)     NULL,
    CONSTRAINT [pk_inc_informe_preliminar_id] PRIMARY KEY NONCLUSTERED ([inc_informe_preliminar_id] ASC) WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF)
);


GO

