CREATE TABLE [dbo].[inc_informe_final_accidentado] (
    [inc_informe_final_accidentado_id] NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [inc_informe_final_id]             NUMERIC (10)    NULL,
    [inc_tipo_involucrado_id]          NUMERIC (10)    NULL,
    [tipo_involucrado_nombre]          VARCHAR (200)   NULL,
    [g_rol_empresa_id]                 NUMERIC (10)    NULL,
    [rol_empresa_nombre]               VARCHAR (100)   NULL,
    [fb_empleado_id]                   NUMERIC (10)    NULL,
    [empleado_codigo]                  VARCHAR (50)    NULL,
    [nombreCompleto]                   VARCHAR (200)   NULL,
    [dni]                              VARCHAR (20)    NULL,
    [fb_area_id]                       NUMERIC (10)    NULL,
    [area_codigo]                      VARCHAR (50)    NULL,
    [area_nombre]                      VARCHAR (200)   NULL,
    [fb_cargo_id]                      NUMERIC (10)    NULL,
    [cargo_codigo]                     VARCHAR (50)    NULL,
    [cargo_nombre]                     VARCHAR (200)   NULL,
    [fb_puesto_trabajo_id]             NUMERIC (10)    NULL,
    [puesto_trabajo_codigo]            VARCHAR (50)    NULL,
    [puesto_trabajo_nombre]            VARCHAR (200)   NULL,
    [fb_empresa_especializada_id]      NUMERIC (10)    NULL,
    [razon_social]                     VARCHAR (100)   NULL,
    [empresa_ruc]                      VARCHAR (50)    NULL,
    [inc_grado_instruccion_id]         NUMERIC (10)    NULL,
    [grado_instruccion_nombre]         VARCHAR (100)   NULL,
    [inc_condicion_civil_id]           NUMERIC (10)    NULL,
    [condicion_civil_nombre]           VARCHAR (100)   NULL,
    [edad]                             NUMERIC (2)     NULL,
    [procedencia]                      VARCHAR (250)   NULL,
    [experiencia_uea_aa]               NUMERIC (2)     NULL,
    [experiencia_uea_mm]               NUMERIC (2)     NULL,
    [experiencia_uea_formateada]       VARCHAR (50)    NULL,
    [experiencia_total_aa]             NUMERIC (2)     NULL,
    [experiencia_total_mm]             NUMERIC (2)     NULL,
    [experiencia_total_formateada]     VARCHAR (50)    NULL,
    [tiempo_servicio_ecm_aa]           NUMERIC (2)     NULL,
    [tiempo_servicio_ecm_mm]           NUMERIC (2)     NULL,
    [tiempo_servicio_formateada]       VARCHAR (50)    NULL,
    [experiencia_ocupacion_aa]         NUMERIC (2)     NULL,
    [experiencia_ocupacion_mm]         NUMERIC (2)     NULL,
    [experiencia_ocupacion_formateada] VARCHAR (50)    NULL,
    [inc_categoria_lesion_id]          NUMERIC (10)    NULL,
    [categoria_lesion_nombre]          VARCHAR (200)   NULL,
    [inc_tipo_descanso_medico_id]      NUMERIC (10)    NULL,
    [tipo_descanso_medico_nombre]      VARCHAR (200)   NULL,
    [diagnostico]                      VARCHAR (MAX)   NULL,
    [descanso_medico_probable]         NUMERIC (4)     NULL,
    [descanso_medico_real]             NUMERIC (10)    NULL,
    [inc_tipo_contacto_id]             NUMERIC (10)    NULL,
    [tipo_contacto_nombre]             VARCHAR (200)   NULL,
    [inc_tipo_lesion_anatomica_id]     NUMERIC (10)    NULL,
    [lesion_anatomica_codigo]          VARCHAR (50)    NULL,
    [tipo_lesion_anatomica_nombre]     VARCHAR (200)   NULL,
    [dias_perdidos_estimados]          NUMERIC (4)     NULL,
    [inc_tipo_turno_id]                NUMERIC (10)    NULL,
    [tipo_turno_nombre]                VARCHAR (200)   NULL,
    [inc_sistema_trabajo_id]           NUMERIC (10)    NULL,
    [sistema_trabajo_nombre]           VARCHAR (200)   NULL,
    [inc_numero_dias_turno_id]         NUMERIC (10)    NULL,
    [numero_dias_turno_nombre]         VARCHAR (200)   NULL,
    [inc_tipo_reporte_id]              NUMERIC (10)    NULL,
    [inc_tipo_incapacidad_id]          NUMERIC (10)    NULL,
    [remuneracion]                     NUMERIC (10, 2) NULL,
    [fb_area_trabajo_id]               NUMERIC (10)    NULL,
    [area_trabajo_nombre]              VARCHAR (200)   NULL,
    [created]                          DATETIME        NULL,
    [created_by]                       NUMERIC (10)    NULL,
    [updated]                          DATETIME        NULL,
    [updated_by]                       NUMERIC (10)    NULL,
    [owner_id]                         NUMERIC (10)    NULL,
    [is_deleted]                       NUMERIC (1)     NULL,
    [num_trab_centro_lab]              NUMERIC (5)     NULL,
    [num_trab_afil_sctr]               NUMERIC (5)     NULL,
    [num_trab_no_afil_sctr]            NUMERIC (5)     NULL,
    [g_aseguradora_id]                 NUMERIC (10)    NULL,
    [aseguradora_nombre]               VARCHAR (100)   NULL,
    [g_tipo_contrato_id]               NUMERIC (10)    NULL,
    [tipo_contrato_nombre]             VARCHAR (100)   NULL,
    [horas_jornada_laboral]            NUMERIC (5)     NULL,
    CONSTRAINT [PK_inc_informe_final_accidentado] PRIMARY KEY CLUSTERED ([inc_informe_final_accidentado_id] ASC)
);


GO

