CREATE TABLE [dbo].[SC_ACCESS] (
    [SC_ACCESS_ID]      NUMERIC (10)   NOT NULL,
    [SC_MODULE_ID]      NUMERIC (10)   NULL,
    [VERSION]           NVARCHAR (20)  NULL,
    [CREATED]           DATETIME       NULL,
    [CREATED_BY]        NUMERIC (10)   NULL,
    [UPDATED]           DATETIME       NULL,
    [UPDATED_BY]        NUMERIC (10)   NULL,
    [OWNER_ID]          NUMERIC (10)   NULL,
    [SC_ROLE_ID]        NUMERIC (10)   NULL,
    [SC_ACCESS_TYPE_ID] NUMERIC (10)   NULL,
    [IS_DELETED]        NUMERIC (1)    NULL,
    [CODE]              NVARCHAR (100) NULL,
    [NAME]              NVARCHAR (100) NULL,
    CONSTRAINT [PK_SC_ACCESS] PRIMARY KEY CLUSTERED ([SC_ACCESS_ID] ASC),
    CONSTRAINT [FK_ACCESS_SC_ACCESS_TYPE] FOREIGN KEY ([SC_ACCESS_TYPE_ID]) REFERENCES [dbo].[SC_ACCESS_TYPE] ([SC_ACCESS_TYPE_ID]),
    CONSTRAINT [FK_ACCESS_SC_ROLE] FOREIGN KEY ([SC_ROLE_ID]) REFERENCES [dbo].[SC_ROLE] ([SC_ROLE_ID])
);


GO

