CREATE TABLE [dbo].[SC_MODULE] (
    [SC_MODULE_ID]       NUMERIC (10)   NOT NULL,
    [SC_MODULE_TYPE_ID]  NUMERIC (10)   NULL,
    [SC_TABLE_ID]        NUMERIC (10)   NULL,
    [CODE]               NVARCHAR (200) NULL,
    [NAME]               NVARCHAR (200) NULL,
    [DESCRIPTION]        NVARCHAR (200) NULL,
    [ITEM_ORDER]         NUMERIC (3)    NULL,
    [MODULE_CALL]        NUMERIC (10)   NULL,
    [MODULE_ICON]        NVARCHAR (200) NULL,
    [URL]                NVARCHAR (400) NULL,
    [IS_LEAF]            NUMERIC (1)    NULL,
    [CREATED]            DATETIME       NULL,
    [CREATED_BY]         NUMERIC (10)   NULL,
    [UPDATED]            DATETIME       NULL,
    [UPDATED_BY]         NUMERIC (10)   NULL,
    [OWNER_ID]           NUMERIC (10)   NULL,
    [INCLUDING_PAGE]     NVARCHAR (200) NULL,
    [SC_SUPER_MODULE_ID] NUMERIC (10)   NULL,
    [GENERIC_TYPE]       NUMERIC (1)    NULL,
    [IS_DELETED]         NUMERIC (1)    NULL,
    [JSON_CONFIG]        NVARCHAR (500) NULL,
    [IS_ENABLED]         NUMERIC (1)    NULL,
    [IS_VISIBLE]         NUMERIC (1)    NULL,
    CONSTRAINT [PK_SC_MODULE] PRIMARY KEY CLUSTERED ([SC_MODULE_ID] ASC),
    CONSTRAINT [FK_MODULE_SC_MODULE_TYPE] FOREIGN KEY ([SC_MODULE_TYPE_ID]) REFERENCES [dbo].[SC_MODULE_TYPE] ([SC_MODULE_TYPE_ID])
);


GO

