CREATE TABLE [dbo].[SC_ROLE] (
    [SC_ROLE_ID]  NUMERIC (10)   NOT NULL,
    [CODE]        NVARCHAR (200) NULL,
    [NAME]        NVARCHAR (200) NULL,
    [DESCRIPTION] NVARCHAR (400) NULL,
    [IS_DELETED]  NUMERIC (1)    NULL,
    [CREATED]     DATETIME       NULL,
    [UPDATED]     DATETIME       NULL,
    [CREATED_BY]  NUMERIC (10)   NULL,
    [UPDATED_BY]  NUMERIC (10)   NULL,
    [OWNER_ID]    NUMERIC (10)   NULL,
    [fb_home_id]  NUMERIC (10)   NULL,
    CONSTRAINT [PK_SC_ROLE] PRIMARY KEY CLUSTERED ([SC_ROLE_ID] ASC)
);


GO

