CREATE TABLE [dbo].[SC_SUPER_MODULE] (
    [SC_SUPER_MODULE_ID] NUMERIC (10)   NOT NULL,
    [CODE]               NVARCHAR (50)  NULL,
    [NAME]               NVARCHAR (100) NULL,
    [ITEM_ORDER]         NUMERIC (5)    NULL,
    [SUPER_MODULE_ICON]  NVARCHAR (200) NULL,
    [DESCRIPTION]        NVARCHAR (200) NULL,
    [CREATED]            DATETIME       NULL,
    [UPDATED]            DATETIME       NULL,
    [IS_DELETED]         NUMERIC (1)    NULL,
    [CREATED_BY]         NUMERIC (10)   NULL,
    [UPDATED_BY]         NUMERIC (10)   NULL,
    [OWNER_ID]           NUMERIC (10)   NULL,
    CONSTRAINT [PK_SC_SUPER_MODULE] PRIMARY KEY CLUSTERED ([SC_SUPER_MODULE_ID] ASC)
);


GO

