CREATE TABLE [dbo].[SC_USER] (
    [SC_USER_ID]                  NUMERIC (10)   IDENTITY (1, 1) NOT NULL,
    [USER_LOGIN]                  NVARCHAR (200) NULL,
    [TELEPHONE]                   NVARCHAR (200) NULL,
    [PASSWORD]                    NVARCHAR (200) NULL,
    [EMAIL]                       VARCHAR (200)  NULL,
    [ACTIVE]                      NUMERIC (8)    CONSTRAINT [DF__SC_USER__ACTIVE__182C9B23] DEFAULT ((0)) NULL,
    [FB_LANGUAGE_ID]              NUMERIC (10)   NULL,
    [CODE]                        VARCHAR (200)  NULL,
    [NAME]                        VARCHAR (400)  NULL,
    [SESSION_CONTROL]             NUMERIC (1)    NULL,
    [DESCRIPTION]                 VARCHAR (500)  NULL,
    [DNI]                         VARCHAR (200)  NULL,
    [CREATED]                     DATETIME       NULL,
    [UPDATED]                     DATETIME       NULL,
    [FB_HISTORY_ID]               NUMERIC (10)   NULL,
    [IS_DELETED]                  NUMERIC (1)    CONSTRAINT [DF__SC_USER__IS_DELE__1920BF5C] DEFAULT ((0)) NULL,
    [CREATED_BY]                  NUMERIC (10)   NULL,
    [UPDATED_BY]                  NUMERIC (10)   NULL,
    [OWNER_ID]                    NUMERIC (10)   NULL,
    [fb_empleado_id]              NUMERIC (10)   NULL,
    [tipo_usuario]                VARCHAR (50)   NULL,
    [id_empresa]                  NUMERIC (10)   NULL,
    [tipo_empresa]                VARCHAR (100)  NULL,
    [start_date]                  DATETIME       NULL,
    [end_date]                    DATETIME       NULL,
    [correo]                      VARCHAR (200)  NULL,
    [nombre_empleado]             VARCHAR (200)  NULL,
    [confirmar_contrasena]        VARCHAR (200)  NULL,
    [bloqueado]                   NUMERIC (1)    NULL,
    [ultimo_acceso]               DATETIME       NULL,
    [numero_intentos]             NUMERIC (5)    NULL,
    [remote_ip]                   VARCHAR (100)  NULL,
    [session_string]              VARCHAR (100)  NULL,
    [excluye_ad]                  NUMERIC (1)    NULL,
    [fb_cliente_id]               NUMERIC (10)   NULL,
    [fb_empresa_especializada_id] NUMERIC (10)   NULL,
    [g_rol_empresa_id]            NUMERIC (10)   NULL,
    CONSTRAINT [PK_SC_USER] PRIMARY KEY CLUSTERED ([SC_USER_ID] ASC),
    CONSTRAINT [FK_USER_FB_HISTORY] FOREIGN KEY ([FB_HISTORY_ID]) REFERENCES [dbo].[FB_HISTORY] ([FB_HISTORY_ID]),
    CONSTRAINT [FK_USER_FB_LANGUAJE] FOREIGN KEY ([FB_LANGUAGE_ID]) REFERENCES [dbo].[FB_LANGUAGE] ([FB_LANGUAGE_ID])
);


GO

