CREATE TABLE [dbo].[SC_USER_GROUP] (
    [SC_USER_GROUP_ID] NUMERIC (10)  IDENTITY (1, 1) NOT NULL,
    [SC_GROUP_ID]      NUMERIC (10)  NULL,
    [SC_USER_ID]       NUMERIC (10)  NULL,
    [VERSION]          NVARCHAR (20) NULL,
    [CREATED]          DATETIME      NULL,
    [UPDATED]          DATETIME      NULL,
    [IS_DELETED]       NUMERIC (1)   NULL,
    [CREATED_BY]       NUMERIC (10)  NULL,
    [UPDATED_BY]       NUMERIC (10)  NULL,
    [OWNER_ID]         NUMERIC (10)  NULL,
    CONSTRAINT [PK_SC_USER_GROUP] PRIMARY KEY CLUSTERED ([SC_USER_GROUP_ID] ASC)
);


GO

